In [4]:
import numpy as np

In [5]:
angka =[1,2,3]

In [6]:
angkanp = np.array(angka)

In [7]:
angkanp

array([1, 2, 3])

In [8]:
angka*3


[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
angkanp*3

array([3, 6, 9])

In [11]:
versilist =[[1,2,3],[4,5,6],[7,8,9]]
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])